import subprocess
from pathlib import Path

CTL = "/home/zhengyuesong/Tools/survey-tool/surveyctl.py"
PROJECT = str(Path.cwd())
RUN = "E010-R-008-full-lasot-natural-replay-grounding-query-role-audit-n1400-640"

fields = {
"run_type": "experiment_code_edit",
"purpose": "尽可能复刻已批准但未执行的 E008-R-001 role audit 协议到完整可核验 LaSOT：先对每个 sequence 自然生成并归档 response/IoU/attention，再仅对精确 replay 对齐样本提取同一自然 Query-bbox p−1 rows 的 Q→Q[G]、Q→R[G]、G→R[G]、Q→Q[L] 注意力，检验冻结 grounding heads 在 query image 上的空间角色。",
"necessity": "R-007 仅能离线读取 R-001 的 140 个冻结 artifacts，不能扩大样本。完整 LaSOT 审计证明有 70 类、1400 条 sequence、3517342 图像、3517342 条标注且每条 sequence 的首/末有效 bbox 图片均存在。E008-R-001 已定义最贴近问题的四边角色审计，但其 140 条上游 natural output/replay 资产并未覆盖完整 LaSOT；必须先构造新的自然输出与 attention artifacts，才能做同协议的扩容复现。",
"evidence_basis": "复刻对象为 E008-R-001-grounding-heads-query-image-role-audit-n140-640：同一自然 Query bbox token 的 p−1 rows、Qwen3-VL-8B-Instruct+IPLoc-ID LoRA、bf16 eager、max_side=640，G-heads=L15H13/L16H23/L18H15，L-heads=L18H15/L19H03/L22H00/L20H08，以及 Q→Q[G]/Q→R[G]/G→R[G]/Q→Q[L] 四边比较。数据盘只读审计：mechanism/dataset/LaSOT -> /defaultShare/pubdata/LaSOT；完整 sequence-id 排序 SHA-256=3a3b8834337bdab6d8a8595f81fef848bacecb7f312dc8d3941a6ef62e37d760。",
"implementation_summary": "在 mechanism/iplocid 的实际公共模块中新增/扩展完整 LaSOT manifest builder、natural collection 与 role-audit pipeline，复用已有 records、prompt、coordinate、span、attention metrics、generation/replay 模块及 E008 role-audit 定义。禁止复制一份模型 runner 或修改上游 R-001/R-003/R-006/R-007。执行前先对 4 条固定 smoke 做路径、bbox、natural response、token row/span 和 exact replay 门禁；门禁通过后才运行完整预冻结 manifest。",
"implementation_details": "Phase A（数据）：从 mechanism/dataset/LaSOT/LaSOT 的每个 category/sequence 读取 groundtruth.txt；每条取第一个合法 [x,y,w,h] 对应帧为 reference、最后一个合法 bbox 对应帧为 query。路径以真实 shared root 写入，不使用旧 data/ICL_tracking 前缀。物化 JSONL + SHA-256，保存 sequence/category/frame ids、image sizes、bbox、GT occupancy 的可重算输入。Phase B（自然采集）：严格原 IPLoc-ID 1-shot prompt，自然生成 query bbox 与 Yes/No，不用 GT teacher force；保存 response、parse status、natural IoU、Query-bbox token positions及全头或审计所需 raw attention/spans。Phase C（exact replay）：只对自然 response/rows/spans 能逐 token 精确复现的记录，重放相同 response，提取四边 raw maps。Phase D（角色审计）：冻结 E008 G/L head sets，逐头和等权 ensemble 报 fractional GT mass、area-normalized enrichment、raw argmax pointing、S50、retained-mass token-fIoU/AUC，及 R-007 同定义 S30/Core30Hit/S30IoU/Largest4NHit/Largest4NIoU；保存 fixed heatmaps。",
"data_definition": "主数据为完整 LaSOT 1400 sequences（70 category×20 sequence），每条仅一组 reference/query，sequence 是统计与split单位。不是官方 LaSOT benchmark split；训练暴露未知。预冻结 sequence-group split：每类以 SHA-256(seed=20260830, category/sequence) 的稳定排序分配 10 条 discovery、10 条 evaluation，故 discovery=700、evaluation=700，类别均衡且 sequence 零重叠。E008 风格的 correct/error 仅根据本 Run 自然正样本的 parsed output 和 IoU 分层：correct=positive 且 IoU≥0.7；error=positive 且 IoU<0.1；middle/nonpositive/unparsed/replay failure 显式单列，绝不用于选择 head 或静默丢弃。",
"data_scale": "预注册尝试完整 1400 条自然 collection；primary spatial evaluation 为所有通过完整性门禁和 exact replay 的 evaluation split 记录，分母、每类计数、失败原因完整报告。discovery split 仅允许用于预注册的 E008 可复刻 head-role quality/sanity summary，不得改变冻结 G/L heads、阈值、prompt、样本选择或最终 evaluation。若运行资源不足，允许按预物化 manifest 的连续 shard 恢复，但只能完整完成 1400 或明确以未完成/无科学结论停止，禁止事后删减为有利子集。",
"model_config": "Qwen3-VL-8B-Instruct + 原 IPLoc-ID 1-shot LoRA；bf16 eager attention；max_side=640；官方 IPLoc prompt/processor/EOS 与 E008-R-001 尽可能一致。记录 base model、LoRA、processor、代码 commit、CUDA/Python、manifest、prompt/template 和 source-data sequence-list SHA-256。不得加载其他模型，不做 activation/attention rewrite，不 teacher-force 生成阶段。",
"variables_controls": "冻结处理头：G=[L15H13,L16H23,L18H15]，L=[L18H15,L19H03,L22H00,L20H08]。主四边：A=natural Query-bbox p−1 rows×G→Query keys；B=相同 rows×G→Reference keys；C=Reference bbox p−1 rows×G→Reference keys（定义性 grounding 边，仅 exact replay）；D=natural Query-bbox p−1 rows×L→Query keys。逐 head 报告；Top3/Top4 等权 ensemble 仅为汇总，不按 GT 或 outcome 加权。控制为 all-head mean、同层随机 head sets（预物化 seed）和 G/L 交集 L18H15 单独报告。",
"metric_definition": "复刻 E008 主指标：fractional_gt_mass=sum(A*w)；area_normalized_enrichment=(sum(A*w)/sum(A))/(sum(w)/N)；pointing_rate=argmax token 与 GT occupancy>0 的比例；S50；retained_mass_fiou_auc=对 rho=0.05..0.95 的 fractional-token IoU 平均。扩展且固定报告 R-007 的 binary token-grid 空间质量：S30 为 attention 降序取 ceil(0.30N)、flattened index stable tie-break；G=occupancy>0；Core30Hit、S30IoU、S30 的最大上下左右 4-neighbor 连通块 Cmax、Largest4NHit、Largest4NIoU。所有比较按 sequence bootstrap（≥1000 次、固定 seed）给 correct-error 和边间差的95% CI；主结果为 evaluation split，discovery/all 仅补充。",
"integrity_gates": "G1 source root、1400 sequence-id hash、每条 reference/query 图像存在、groundtruth 行数=图像数、bbox 有限且 w/h>0；任一失败保留原因。G2 category/sequence group split 零重叠、每类 discovery/evaluation 各10条、split manifest/hash 在启动模型前物化。G3 natural generation 不读 query GT，记录原始 response 和 parse；不得使用 GT 修复生成框。G4 每个 attention 样本的自然 response token、Query-bbox p−1 rows、Reference bbox p−1 rows（如适用）、双图 span/grid 与 replay 必须精确对齐；不对齐只计入 replay failure，不伪造 attention。G5 所有 map finite/nonnegative、GT occupancy 非空、shape匹配；G6 G/L heads 与 max_side/prompt 由 config hash 锁定，禁止根据 outcome、GT 或中途结果重选。G7 逐图/汇总 n 必须守恒，所有 exclusion/failure按 split/category/phase 报告；G8 fixed visualizations 共用色标且显示 raw metrics。",
"expected_outcome": "允许并将如实区分：H1 grounding heads 的 Q→Q 空间质量与 correct/error 关联，支持跨角色 signature；H2 G→R 质量保留而 G→Q 弥散，支持 reference-side role division；H3 仅交集 L18H15 有跨边质量；或全部关系在扩大 evaluation 中消失。扩大数据用于检验稳定性，不允许以结果调整 heads/rows/cutoffs。",
"acceptance_criteria": "仅在审核和执行授权后：代码单测覆盖 LaSOT 路径/annotation、split determinism/zero overlap、bbox/frame mapping、row/span exactness、S30/4-neighbor tie-break；4条 smoke 全部保存；1400 条 manifest 与完整性表可复算；natural collection/replay 的每阶段分母与失败原因齐全；evaluation 上四边×head 的 E008 指标、R-007 扩展空间指标、bootstrap CI、frozen correct/error 分层和固定图齐全；raw JSONL、summary、metrics、manifest hashes 和环境/commit 存档。若 G1-G6 任一核心 gate 大范围失败，停止并报告 failure，不产出机制结论。",
"dependencies": "依赖共享 LaSOT root 的只读可用性、当前 IPLoc-ID model/LoRA/processor 的可加载性，以及 E008 public role-audit 的实现可验证。R-003/R-006 heads 不作为本 Run 的选择 authority；本 Run 只复刻 E008 的 G/L 角色审计冻结集合。不得修改已完成 E010-R-007 或使用其 140 条数据补足/混合完整 LaSOT。",
"limitations": "本 Run 是自然生成后 exact replay 的 attention 观察；只对 replay exact 样本的空间读出可能有选择性，必须报告 replay rate 与失败构成。LaSOT 单目标 tracking sequences 不构成多实例 identity-binding 测试；training exposure 未知；attention/readout 不证明头的因果必要性、信息内容、identity matching 或行为改善。C=Reference bbox row 是 E008 定义性对照，不得被重新解释为用户所说的 reference heads 发现。",
"claim_boundary": "最多评估 E008 冻结 grounding/localization heads 在完整 LaSOT、sequence-held-out自然样本上四种注意力边的空间签名、可迁移性及其与 natural outcome 的观察性关联；不重新定义 E010 的 query/reference heads，不证明因果、identity routing 或泛化到 GOT10k/TAO。",
"audit_paths": "source=/defaultShare/archive/liuwenchu/projects/IPLoc/mechanism/dataset/LaSOT/LaSOT；implementation=/defaultShare/archive/liuwenchu/projects/IPLoc/mechanism/iplocid/iplocid/{datasets,attention,inference,pipelines}；reference protocol=shell/06_experiments/E-008/runs/E008-R-001-grounding-heads-query-image-role-audit-n140-640.md；outputs=/defaultShare/archive/liuwenchu/projects/IPLoc/experiments/E-010/" + RUN,
"status": "planned",
"workspace_id": "02",
"seed": "20260830",
"research_question": "在完整 LaSOT 1400 sequence 的自然 Query-bbox 生成与 exact replay 上，E008 冻结 grounding heads 是否在 Query image 上显示可迁移的空间定位 signature，还是主要保留 Reference grounding 角色？",
"hypothesis": "若跨角色作用稳定，evaluation 上 G-head Q→Q 的 GT spatial metrics 与 correct-error 分层将优于同层随机并接近 localization-head Q→Q；若角色分工成立，则 G→R 保持而 G→Q 明显更弱。",
"metric_plan": "E008 fractional mass/enrichment/pointing/S50/fIoU-AUC 为主；R-007 S30/Cmax IoU 为严格空间补充；evaluation sequence bootstrap CI 为主推断，all/discovery 仅描述性。",
"architecture_plan": "先物化并哈希完整 LaSOT sequence manifest，再自然 collection，随后 exact replay 和公共 role-audit；每步都有独立可恢复 artifact 与完整性 gate，禁止从旧140 artifacts或未对齐记录推断新规模结果。"
}
cmd = ["python3", CTL, "--project", PROJECT, "run", "create", "E-010", "--id", RUN, "--variant", "完整LaSOT自然重放的E008 grounding/query角色审计（n=1400，640）"]
for key, value in fields.items():
    cmd.extend(["--" + key.replace("_", "-"), value])
print(subprocess.run(cmd, check=True, text=True, capture_output=True).stdout)
print(subprocess.run(["python3", CTL, "--project", PROJECT, "run", "submit-review", RUN, "--message", "用户授权创建：基于完整LaSOT 1400 sequence、尽可能复刻E008-R-001的自然生成+exact replay+四边角色审计；请审核数据/模型/运行范围。未获批准和执行授权前不修改远端代码、不物化manifest、不启动模型。"], check=True, text=True, capture_output=True).stdout)
